# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        WeavidBundle\Entity\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        weavid_database_provider:
            entity:
                class: WeavidBundle:User
                property: email


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        #dev:
        #    pattern: ^/(_(profiler|wdt)|css|images|js)/
        #    security: false

        main:
            anonymous: ~
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
                require_previous_session: false
            provider: weavid_database_provider
            logout:
                path: /logout
            remember_me:
                secret: '%secret%'
                lifetime: 604800 # 1 week in seconds
                path: /

#    access_control:
#        - { path: ^/registration, allow_if: "!has_role('ROLE_USER')" }
#        - { path: ^/forgot, allow_if: "!has_role('ROLE_USER')" }
#        - { path: ^/verify, allow_if: "!has_role('ROLE_USER')" }
#        - { path: ^/login, allow_if: "!has_role('ROLE_USER')" }
