# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
imports:
    - { resource: parameters.yml }

parameters:
#    parameter_name: value

services:
    simple_form_authenticator:
        class:  WeavidBundle\Security\SimpleFormAuthenticator
        arguments: ["@security.password_encoder", "@doctrine.orm.entity_manager"]
    my.listener:
        class: WeavidBundle\EventListener\TimestampSubscriber
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }
    app.vimeo:
        class: Vimeo\Vimeo
        arguments: ['%client_id%', '%client_secret%', '%access_token%']
